runtime: python39  # Or python311 if using Python 3.11
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1  # Smallest free-tier instance
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0  # Ensures no costs when idle
  max_instances: 1  # Prevents exceeding free tier